import { Modes } from "../_types/enums";

export const NOTES_FOLDER = Modes.NOTES;
export const DEPRECATED_DOCS_FOLDER = Modes.DEPRECATED_DOCS;

export const QUOTES = [
    "Nothing... a whole lot of nothing.",
    "What's in the box?!",
    "Hello? Is there anybody in there?",
    "You've got nothing. I've got nothing. Let's do nothing.",
    "The journey of a thousand miles begins with a single step.",
    "Silence is golden.",
    "There's nothing to see here.",
    "Empty.",
    "Hello darkness, my old friend.",
    "I'll be back.",
    "Just start.",
    "This is not the note you are looking for.",
    "I feel like a blank canvas.",
    "Alright, alright, alright.",
    "There is no spoon.",
    "Waiting.",
    "// TODO: Add content here",
    "Error 404: Note not found.",
    "Make it so.",
    "Hello, world!",
    "The rest is still unwritten.",
    "A note about nothing.",
    "What... is your quest?",
    "Where we're going, we don't need roads.",
    "The Nothing is spreading.",
    "This page intentionally left blank.",
    "And now for something completely different.",
    "I'm sorry, Dave. I'm afraid I can't do that.",
    "Space: the final frontier.",
    "Get on with it!",
    "Are you the Keymaster?",
    "All work and no play makes Jack a dull boy.",
    "The sleeper must awaken.",
    "In the beginning...",
    "An enigma, wrapped in a riddle, inside a mystery.",
    "If you build it, he will come.",
    "So it begins.",
    "Engage!",
    "Kept you waiting, huh?",
    "The truth is out there.",
    "Are you still there?",
    "It's dangerous to go alone! Take this.",
    "A long time ago in a galaxy far, far away...",
    "Allons-y!",
    "Follow the white rabbit.",
    "This is the beginning of a beautiful friendship.",
    "Pay no attention to that man behind the curtain.",
    "What we've got here is failure to communicate.",
    "To infinity... and beyond!",
    "Here's Johnny!",
    "You're gonna need a bigger boat.",
    "What is my purpose?",
    "Carpe diem. Seize the day, boys.",
    "It's a dangerous business, Frodo, going out your door.",
    "The first rule of Fight Club is: you do not talk about Fight Club.",
    "I have a bad feeling about this.",
    "Elementary, my dear Watson.",
    "Begin at the beginning.",
    "Open the pod bay doors, HAL.",
    "You had me at 'hello'.",
    "How about a nice game of chess?",
    "The board is set, the pieces are moving."
];