import { createLowlight } from "lowlight";
import javascript from "highlight.js/lib/languages/javascript";
import typescript from "highlight.js/lib/languages/typescript";
import python from "highlight.js/lib/languages/python";
import css from "highlight.js/lib/languages/css";
import html from "highlight.js/lib/languages/xml";
import sql from "highlight.js/lib/languages/sql";
import bash from "highlight.js/lib/languages/bash";
import json from "highlight.js/lib/languages/json";
import yaml from "highlight.js/lib/languages/yaml";
import markdown from "highlight.js/lib/languages/markdown";
import java from "highlight.js/lib/languages/java";
import csharp from "highlight.js/lib/languages/csharp";
import cpp from "highlight.js/lib/languages/cpp";
import c from "highlight.js/lib/languages/c";
import go from "highlight.js/lib/languages/go";
import rust from "highlight.js/lib/languages/rust";
import php from "highlight.js/lib/languages/php";
import ruby from "highlight.js/lib/languages/ruby";
import perl from "highlight.js/lib/languages/perl";
import kotlin from "highlight.js/lib/languages/kotlin";
import swift from "highlight.js/lib/languages/swift";
import dart from "highlight.js/lib/languages/dart";
import scala from "highlight.js/lib/languages/scala";
import clojure from "highlight.js/lib/languages/clojure";
import haskell from "highlight.js/lib/languages/haskell";
import lua from "highlight.js/lib/languages/lua";
import r from "highlight.js/lib/languages/r";
import matlab from "highlight.js/lib/languages/matlab";
import powershell from "highlight.js/lib/languages/powershell";
import dockerfile from "highlight.js/lib/languages/dockerfile";
import nginx from "highlight.js/lib/languages/nginx";
import apache from "highlight.js/lib/languages/apache";
import makefile from "highlight.js/lib/languages/makefile";
import latex from "highlight.js/lib/languages/latex";
import vhdl from "highlight.js/lib/languages/vhdl";
import verilog from "highlight.js/lib/languages/verilog";
import scss from "highlight.js/lib/languages/scss";
import less from "highlight.js/lib/languages/less";
import shell from "highlight.js/lib/languages/shell";

export const lowlight = createLowlight();

lowlight.register("javascript", javascript);
lowlight.register("js", javascript);
lowlight.register("typescript", typescript);
lowlight.register("ts", typescript);
lowlight.register("python", python);
lowlight.register("py", python);
lowlight.register("css", css);
lowlight.register("html", html);
lowlight.register("sql", sql);
lowlight.register("bash", bash);
lowlight.register("json", json);
lowlight.register("yaml", yaml);
lowlight.register("markdown", markdown);
lowlight.register("java", java);
lowlight.register("csharp", csharp);
lowlight.register("c#", csharp);
lowlight.register("cpp", cpp);
lowlight.register("c++", cpp);
lowlight.register("c", c);
lowlight.register("go", go);
lowlight.register("rust", rust);
lowlight.register("php", php);
lowlight.register("ruby", ruby);
lowlight.register("perl", perl);
lowlight.register("kotlin", kotlin);
lowlight.register("swift", swift);
lowlight.register("dart", dart);
lowlight.register("scala", scala);
lowlight.register("clojure", clojure);
lowlight.register("haskell", haskell);
lowlight.register("lua", lua);
lowlight.register("r", r);
lowlight.register("matlab", matlab);
lowlight.register("powershell", powershell);
lowlight.register("ps1", powershell);
lowlight.register("dockerfile", dockerfile);
lowlight.register("nginx", nginx);
lowlight.register("apache", apache);
lowlight.register("makefile", makefile);
lowlight.register("latex", latex);
lowlight.register("tex", latex);
lowlight.register("vhdl", vhdl);
lowlight.register("verilog", verilog);
lowlight.register("scss", scss);
lowlight.register("less", less);
lowlight.register("shell", shell);
